In [4]:
from pathlib import Path

import esdglider.profiles as prof
import numpy as np

# import pandas as pd
import xarray as xr

from esdglider import gcp, paths, utils

deployment_name = "calanus-20260824"
mode = "rt"

### Consistent variables
# Define directories
home = Path.home()
mnt_path = home / "mnt-gcs"
cac_path = home / "standard-glider-files" / "Cache"
config_path = home / "glider-lab" / "deployment-configs"

# Bucket names and paths
data_in_bucket_name = "swfscesd-glider-deployments-data-in"
data_out_bucket_name = "swfscesd-glider-deployments-data-out"

data_in_path = mnt_path / data_in_bucket_name
data_out_path = mnt_path / data_out_bucket_name

### Mount the relevant bucket(s), get paths
gcp.gcs_mount_bucket(data_out_bucket_name, data_out_path, ro=True)

glider_paths = paths.get_path_glider(
    deployment_name = deployment_name, 
    mode = mode, 
    config_path = config_path, 
    data_in_path = data_in_path, 
    data_out_path = data_out_path, 
    cac_path = cac_path, 
)

In [5]:
ds_raw = xr.load_dataset(glider_paths["tsrawpath"])
df_raw = ds_raw.to_pandas()
display(ds_raw)

<xarray.Dataset> Size: 66MB
Dimensions:                       (time: 141413)
Coordinates:
  * time                          (time) datetime64[ns] 1MB 2026-08-24T18:47:...
    latitude                      (time) float64 1MB nan nan nan ... nan nan nan
    longitude                     (time) float64 1MB nan nan nan ... nan nan nan
Data variables: (12/48)
    m_depth                       (time) float64 1MB 0.9258 nan ... nan 0.1012
    m_heading                     (time) float64 1MB nan nan nan ... nan nan nan
    m_pitch                       (time) float64 1MB nan nan nan ... nan nan nan
    m_roll                        (time) float64 1MB nan nan nan ... nan nan nan
    m_tot_num_inflections         (time) float64 1MB nan nan nan ... nan nan nan
    m_altitude                    (time) float64 1MB nan nan nan ... nan nan nan
    ...                            ...
    sci_solocam_image_files       (time) float64 1MB nan nan nan ... nan nan nan
    distance_over_ground          (time) float64 1MB nan nan nan ... nan nan nan
    source_filename               (time) <U16 9MB 'calanus-2026-235' ... 'cal...
    depth_ctd                     (time) float64 1MB nan nan nan ... nan nan nan
    profile_index                 (time) float64 1MB 0.5 0.5 0.5 ... 530.5 530.5
    profile_direction             (time) float64 1MB -1.0 -1.0 -1.0 ... -1.0 nan
Attributes: (12/61)
    Conventions:               CF-1.8
    Metadata_Conventions:      Unidata Dataset Discovery v1.0, COARDS, CF-1.8
    acknowledgment:            This work was supported by funding from NOAA.
    cdm_data_type:             Trajectory
    comment:                   El Nino 2026; The variable names for this raw ...
    contributor_name:          Heidi Taylor, Jennifer Walsh, Anthony Cossio, ...
    ...                        ...
    summary:                   This glider was deployed as the first of sever...
    time_coverage_end:         20260908T221927
    time_coverage_start:       20260824T184707
    title:                     calanus-20260824T1847
    transmission_system:       IRIDIUM
    wmo_id:

In [6]:
ds_eng = xr.load_dataset(glider_paths["tsengpath"])
df_eng = ds_eng.to_pandas()
display(ds_eng)

ds_sci = xr.load_dataset(glider_paths["tsscipath"])
df_sci = ds_sci.to_pandas()
display(ds_sci)

<xarray.Dataset> Size: 8MB
Dimensions:               (time: 39315)
Coordinates:
  * time                  (time) datetime64[ns] 315kB 2026-08-24T18:47:07.473...
    depth                 (time) float64 315kB 0.9258 0.0 0.0 ... 13.89 11.12
    latitude              (time) float64 315kB 32.75 32.75 32.75 ... 32.37 32.37
    longitude             (time) float64 315kB -117.3 -117.3 ... -118.5 -118.5
Data variables: (12/16)
    heading               (time) float64 315kB 1.236e+11 1.114e+11 ... 0.8326
    pitch                 (time) float64 315kB -0.05411 -0.05411 ... 0.451
    roll                  (time) float64 315kB -0.06109 -0.06109 ... -0.06039
    altitude              (time) float64 315kB 0.0 0.0 0.0 0.0 ... nan nan nan
    battery_voltage       (time) float64 315kB 16.42 16.42 16.42 ... 14.94 14.94
    battery_position      (time) float64 315kB 0.01863 0.01863 ... -0.6101
    ...                    ...
    leak_detect_forward   (time) float64 315kB 2.493 2.493 2.493 ... nan nan nan
    leak_detect_science   (time) float64 315kB 2.491 2.491 2.491 ... nan nan nan
    vacuum                (time) float64 315kB 7.676 7.676 7.676 ... nan nan nan
    distance_over_ground  (time) float64 315kB 0.0 0.0001505 ... 258.4 258.4
    trajectory            (time) <U16 3MB 'calanus-20260824' ... 'calanus-202...
    profile_index         (time) float64 315kB 0.5 0.5 0.5 ... 530.0 530.0 530.0
Attributes: (12/61)
    Conventions:               CF-1.8
    Metadata_Conventions:      Unidata Dataset Discovery v1.0, COARDS, CF-1.8
    acknowledgment:            This work was supported by funding from NOAA.
    cdm_data_type:             Trajectory
    comment:                   El Nino 2026; Engineering-only timeseries
    contributor_name:          Heidi Taylor, Jennifer Walsh, Anthony Cossio, ...
    ...                        ...
    summary:                   This glider was deployed as the first of sever...
    time_coverage_end:         20260908T221302
    time_coverage_start:       20260824T184707
    title:                     calanus-20260824T1847
    transmission_system:       IRIDIUM
    wmo_id:

<xarray.Dataset> Size: 15MB
Dimensions:                      (time: 46996)
Coordinates:
  * time                         (time) datetime64[ns] 376kB 2026-08-24T18:49...
    latitude                     (time) float64 376kB 32.75 32.75 ... 32.37
    longitude                    (time) float64 376kB -117.3 -117.3 ... -118.5
    depth                        (time) float64 376kB 3.565 4.568 ... 321.3
Data variables: (12/39)
    conductivity                 (time) float64 376kB 4.778 4.763 ... 3.57 3.569
    temperature                  (time) float64 376kB 21.91 21.81 ... 8.003
    pressure                     (time) float64 376kB 3.59 4.6 ... 323.7 323.8
    chlorophyll                  (time) float64 376kB 0.1152 0.1296 ... 0.0432
    cdom                         (time) float64 376kB 1.905 1.905 ... 4.263
    backscatter_700              (time) float64 376kB 0.000245 ... 0.0001005
    ...                           ...
    oxygen_saturation_qc         (time) float32 188kB 1.0 1.0 1.0 ... 1.0 1.0
    water_velocity_eastward_qc   (time) float32 188kB 1.0 1.0 1.0 ... 9.0 9.0
    water_velocity_northward_qc  (time) float32 188kB 1.0 3.0 3.0 ... 9.0 9.0
    potential_density_qc         (time) float32 188kB 1.0 1.0 1.0 ... 1.0 1.0
    potential_temperature_qc     (time) float32 188kB 1.0 1.0 1.0 ... 1.0 1.0
    time_qc                      (time) float32 188kB nan nan nan ... nan nan
Attributes: (12/62)
    Conventions:               CF-1.8
    Metadata_Conventions:      Unidata Dataset Discovery v1.0, COARDS, CF-1.8
    acknowledgment:            This work was supported by funding from NOAA.
    cdm_data_type:             Trajectory
    comment:                   El Nino 2026
    contributor_name:          Heidi Taylor, Jennifer Walsh, Anthony Cossio, ...
    ...                        ...
    time_coverage_end:         20260908T213734
    time_coverage_start:       20260824T184907
    title:                     calanus-20260824T1847
    transmission_system:       IRIDIUM
    wmo_id:
    ioos_qc_version:           3.0.0

## Profile checks

In [7]:
# print("-------ENG")
# display(utils.check_profiles(utils.calc_profile_summary(ds_eng, "depth")))
# print("-------SCI")
# display(utils.check_profiles(utils.calc_profile_summary(ds_sci, "depth")))

print("-------RAW")
prof_summ_raw = prof.calc_profile_summary(ds_raw, "m_depth")
prof.check_profiles(prof_summ_raw)
print(f"Dives: {np.count_nonzero(prof_summ_raw.profile_direction.values == 1)}")
print(f"Climbs: {np.count_nonzero(prof_summ_raw.profile_direction.values == -1)}")
display(prof_summ_raw)

-------RAW
Dives: 265
Climbs: 265

,profile_index,profile_direction,profile_phase,start_time,end_time,start_depth,end_depth,min_depth,max_depth,depth_range,min_lon,max_lon,min_lat,max_lat,distance_traveled,num_points,time_at_surface_s,profile_duration_s
0,0.5,0.0,surfacing,2026-08-24 18:47:07.473999872,2026-08-24 18:48:12.104999936,0.925808,0.000000,0.000000,0.925808,0.925808,NaN,NaN,NaN,NaN,NaN,11,64,64.631
1,1.0,1.0,descent,2026-08-24 18:48:16.120999936,2026-08-24 18:51:43.585999872,1.390163,23.145203,1.390163,23.145203,21.755039,NaN,NaN,NaN,NaN,NaN,35,32,207.465
2,1.5,0.0,inflection,2026-08-24 18:51:56.457999872,2026-08-24 18:51:56.457999872,25.908115,25.908115,25.908115,25.908115,0.000000,NaN,NaN,NaN,NaN,NaN,1,0,0.000
3,2.0,-1.0,ascent,2026-08-24 18:51:56.586999808,2026-08-24 18:56:41.004000000,25.443760,0.133478,0.133478,25.443760,25.310282,NaN,NaN,NaN,NaN,NaN,24,64,284.417
4,2.5,0.0,surfacing,2026-08-24 18:56:45.006000128,2026-08-24 19:50:36.152000000,0.110264,0.713817,0.110264,1.526292,1.416028,NaN,NaN,NaN,NaN,NaN,54,3231,3231.146
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1056,528.5,0.0,inflection,2026-09-08 21:03:58.043000064,2026-09-08 21:03:58.043000064,5.954856,5.954856,5.954856,5.954856,0.000000,NaN,NaN,NaN,NaN,NaN,1,0,0.000
1057,529.0,1.0,descent,2026-09-08 21:04:25.809999872,2026-09-08 21:37:08.809999872,11.927073,321.301819,11.927073,321.301819,309.374745,-118.479171,-118.475324,32.366064,32.367063,NaN,306,0,1963.000
1058,529.5,0.0,inflection,2026-09-08 21:37:14.953000192,2026-09-08 21:37:46.987000064,325.283295,325.283295,325.283295,325.283295,0.000000,NaN,NaN,NaN,NaN,NaN,5,0,32.034
1059,530.0,-1.0,ascent,2026-09-08 21:37:59.000000000,2026-09-08 22:14:51.493999872,323.547180,2.158563,2.158563,323.547180,321.388617,-118.473602,-118.468520,32.367960,32.370530,NaN,163,0,2212.494
1060,530.5,0.0,surfacing,2026-09-08 22:15:11.510999808,2026-09-08 22:19:27.750999808,0.000000,0.101234,0.000000,0.216931,0.216931,NaN,NaN,NaN,NaN,NaN,17,256,256.240

In [8]:
# d = ds_sci.where(ds_sci.pressure.isnull(), drop = True)
# d

In [9]:
# idx_list = 6.5, 8.5, 10.5, 14.5, 18.5, 22.5, 30.5, 34.5, 38.5, 58.5, 74.5, 78.5, 82.5, 86.5, 98.5, 118.5, 122.5, 142.5, 166.5, 174.5, 182.5, 190.5, 194.5, 210.5, 218.5, 222.5, 230.5, 242.5, 250.5, 282.5, 294.5, 306.5, 334.5, 358.5, 370.5, 374.5, 410.5, 424.5, 430.5, 438.5, 442.5, 478.5, 494.5, 498.5, 518.5, 526.5, 530.5, 534.5, 538.5, 550.5, 554.5, 558.5, 566.5, 582.5, 594.5, 602.5, 618.5, 630.5, 646.5, 654.5, 666.5, 670.5, 674.5, 678.5, 690.5, 694.5, 702.5, 706.5, 710.5, 714.5, 722.5, 746.5, 750.5, 754.5, 762.5, 766.5, 770.5
# p1 = utils.check_profiles(ds_sci)
# p1e = p1[np.isin(p1["profile_index"], idx_list)]
# p1e

# ds = ds_raw
# dt = "2023-12-19"
# ds_sub1 = ds.sel(time=slice(f"{dt} 08:00", dt))
# ds_sub1

<!-- ## Testing new profile parameters -->

In [10]:
# Testing if eng and sci also need to have points dropped
# ds = ds_eng #ds_sci
# x = ds
# keep = ( 
#     (ds["time"] != np.datetime64("2026-01-31 22:59:03.740000"))
#     & (ds["time"] != np.datetime64("2026-01-31 22:59:05.576000"))
#     & (ds["time"] != np.datetime64("2026-02-09 08:18:59.696000"))
# )
# y = ds.sel(time=keep)

# print(len(x.time))
# print(len(y.time))

## Exploring new profile calculations

In [11]:
ds_touse = ds_raw.copy(deep=True)

vars_keep = ["m_depth", "depth_ctd", "profile_index", "profile_direction"]
#, "longitude", "latitude", 
x_orig = utils.data_var_reorder(ds_touse, vars_keep)
# regions_df_orig = utils.calc_regions(x_orig)
# print(x_orig.profile_index.attrs)

# If necessary, remove points before calculating profiles
# keep_times = ( 
#     (x_orig["time"] != np.datetime64("2026-01-31 22:59:03.740000"))
#     & (x_orig["time"] != np.datetime64("2026-01-31 22:59:05.576000"))
#     & (x_orig["time"] != np.datetime64("2026-02-09 08:18:59.696000"))
# )
# x_orig = x_orig.sel(time=keep_times)

# pgutils.get_profiles_new(x, filt_time=20)
p1, p2, p_opt = prof.findProfiles(
    x_orig.time.values,
    x_orig.m_depth.values,
    # stall=4, 
    # shake=15,
    # interrupt=2000,
    # inversion=20,
    # length=14,
    # period=0,
)
# # Defaults    
# stall=3, #scalar with the maximum vertical displacement when stalled.
# shake=20, #scalar with the maximum duration of a vertical shake.
# interrupt=180, #scalar with the maximum duration of stalled and/or shake intervals during a cast.
# inversion=3, #scalar with the maximum depth inversion allowed during a cast.
# length=10, #scalar with the minimum depth range a cast must span.
# period=0, #scalar with the minimum duration range a cast must last.

orig = ["profile_index_orig", "profile_direction_orig"]
x = x_orig.rename_vars({"profile_index": orig[0], "profile_direction": orig[1]})
x["profile_index"] = ('time', p1, {})
x["profile_direction"] = ('time', p2, {})
x = utils.data_var_reorder(x, (vars_keep + orig))

# x["dives"] = ('time', gt.utils.calc_dive_number(x.time.values, x.depth.values, dive_depth_threshold=15), {})
# display(x)

In [12]:
# Implement specific fixes, if needed

# x["profile_index"].loc[
#     {"time": slice("2026-02-06 18:58", "2026-02-06 19:49:39")}
# ] = 163.0
# x["profile_index"][x["profile_index"] > 163] -= 1

# x["profile_index"].loc[
#     {"time": slice("2026-02-15 11:48:00", "2026-02-15 11:51:21.6")}
# ] = 319
# x["profile_index"].loc[
#     {"time": slice("2026-02-17 18:30:30", "2026-02-17 18:32:57.4")}
# ] = 355
# x["profile_index"].loc[
#     {"time": slice("2026-01-25 01:51", "2026-01-25 01:55")}
# ] = 182

In [13]:
# Create subset, to look at in data wrangler
ds = x
dt = "2026-01-31"
ds_sub = ds.sel(time=slice(f"{dt} 22:59", dt))
ds_sub

<xarray.Dataset> Size: 0B
Dimensions:                       (time: 0)
Coordinates:
  * time                          (time) datetime64[ns] 0B
    latitude                      (time) float64 0B
    longitude                     (time) float64 0B
Data variables: (12/50)
    m_depth                       (time) float64 0B
    depth_ctd                     (time) float64 0B
    profile_index                 (time) float64 0B
    profile_direction             (time) float64 0B
    profile_index_orig            (time) float64 0B
    profile_direction_orig        (time) float64 0B
    ...                            ...
    sci_flbbcd_cdom_units         (time) float64 0B
    sci_flbbcd_bb_units           (time) float64 0B
    sci_solocam_free_disk_space   (time) float64 0B
    sci_solocam_image_files       (time) float64 0B
    distance_over_ground          (time) float64 0B
    source_filename               (time) <U16 0B
Attributes: (12/61)
    Conventions:               CF-1.8
    Metadata_Conventions:      Unidata Dataset Discovery v1.0, COARDS, CF-1.8
    acknowledgment:            This work was supported by funding from NOAA.
    cdm_data_type:             Trajectory
    comment:                   El Nino 2026; The variable names for this raw ...
    contributor_name:          Heidi Taylor, Jennifer Walsh, Anthony Cossio, ...
    ...                        ...
    summary:                   This glider was deployed as the first of sever...
    time_coverage_end:         20260908T221927
    time_coverage_start:       20260824T184707
    title:                     calanus-20260824T1847
    transmission_system:       IRIDIUM
    wmo_id:

In [14]:
# Check profiles
prof_summ = prof.calc_profile_summary(x, "m_depth")
prof.check_profiles(prof_summ)
print(f"Dives: {np.count_nonzero(prof_summ.profile_direction.values == 1)}")
print(f"Climbs: {np.count_nonzero(prof_summ.profile_direction.values == -1)}")

# gg = prof_summ[prof_summ.profile_index.isin([6.5, 10.5, 14.5, 18.5, 26.5, 30.5, 50.5, 62.5, 70.5, 78.5, 110.5, 114.5, 158.5, 210.5, 218.5, 222.5, 270.5, 274.5, 346.5, 350.5, 362.5, 430.5, 440.5, 478.5, 482.5, 490.5, 494.5, 510.5, 562.5, 594.5, 602.5, 646.5, 666.5, 702.5, 714.5, 738.5, 764.5, 770.5])]
# display(gg)

prof_summ

Dives: 265
Climbs: 265

,profile_index,profile_direction,profile_phase,start_time,end_time,start_depth,end_depth,min_depth,max_depth,depth_range,min_lon,max_lon,min_lat,max_lat,distance_traveled,num_points,time_at_surface_s,profile_duration_s
0,0.5,0.0,surfacing,2026-08-24 18:47:07.473999872,2026-08-24 18:48:12.104999936,0.925808,0.000000,0.000000,0.925808,0.925808,NaN,NaN,NaN,NaN,NaN,11,64,64.631
1,1.0,1.0,descent,2026-08-24 18:48:16.120999936,2026-08-24 18:51:43.585999872,1.390163,23.145203,1.390163,23.145203,21.755039,NaN,NaN,NaN,NaN,NaN,35,32,207.465
2,1.5,0.0,inflection,2026-08-24 18:51:56.457999872,2026-08-24 18:51:56.457999872,25.908115,25.908115,25.908115,25.908115,0.000000,NaN,NaN,NaN,NaN,NaN,1,0,0.000
3,2.0,-1.0,ascent,2026-08-24 18:51:56.586999808,2026-08-24 18:56:41.004000000,25.443760,0.133478,0.133478,25.443760,25.310282,NaN,NaN,NaN,NaN,NaN,24,64,284.417
4,2.5,0.0,surfacing,2026-08-24 18:56:45.006000128,2026-08-24 19:50:36.152000000,0.110264,0.713817,0.110264,1.526292,1.416028,NaN,NaN,NaN,NaN,NaN,54,3231,3231.146
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1056,528.5,0.0,inflection,2026-09-08 21:03:58.043000064,2026-09-08 21:03:58.043000064,5.954856,5.954856,5.954856,5.954856,0.000000,NaN,NaN,NaN,NaN,NaN,1,0,0.000
1057,529.0,1.0,descent,2026-09-08 21:04:25.809999872,2026-09-08 21:37:08.809999872,11.927073,321.301819,11.927073,321.301819,309.374745,-118.479171,-118.475324,32.366064,32.367063,NaN,306,0,1963.000
1058,529.5,0.0,inflection,2026-09-08 21:37:14.953000192,2026-09-08 21:37:46.987000064,325.283295,325.283295,325.283295,325.283295,0.000000,NaN,NaN,NaN,NaN,NaN,5,0,32.034
1059,530.0,-1.0,ascent,2026-09-08 21:37:59.000000000,2026-09-08 22:14:51.493999872,323.547180,2.158563,2.158563,323.547180,321.388617,-118.473602,-118.468520,32.367960,32.370530,NaN,163,0,2212.494
1060,530.5,0.0,surfacing,2026-09-08 22:15:11.510999808,2026-09-08 22:19:27.750999808,0.000000,0.101234,0.000000,0.216931,0.216931,NaN,NaN,NaN,NaN,NaN,17,256,256.240

In [15]:
# Visual sanity check
prof_summ.start_depth.round(0)

0         1.0
1         1.0
2        26.0
3        25.0
4         0.0
        ...
1056      6.0
1057     12.0
1058    325.0
1059    324.0
1060      0.0
Name: start_depth, Length: 1061, dtype: float64

In [ ]:
# Check profiles on eng and sci datasets
print("ENG------")
x_eng = prof.join_profiles(ds_eng, prof_summ, {})
prof_summ_eng = prof.calc_profile_summary(x_eng, "depth")
display(prof.check_profiles(prof_summ_eng))

print("SCI------")
x_sci = prof.join_profiles(ds_sci, prof_summ, {})
prof_summ_sci = prof.calc_profile_summary(x_sci, "depth")
display(prof.check_profiles(prof_summ_sci))

In [ ]:
# regions_df_orig = utils.calc_regions(x_orig)
# regions_df = utils.calc_regions(x)
# # display(regions_df)
# # print(np.argwhere(regions_df_orig.profile_description == np.roll(regions_df_orig.profile_description, 1)))

# # print(regions_df["profile_direction"].value_counts())
# print("------------")
# print(f"Climbs orig: {np.count_nonzero(regions_df_orig["profile_direction"] == -1)}")
# print(f"Dives orig: {np.count_nonzero(regions_df_orig["profile_direction"] == 1)}")
# utils.check_profiles(x_orig)

# print("------------")
# print(f"Climbs: {np.count_nonzero(regions_df["profile_direction"] == -1)}")
# print(f"Dives: {np.count_nonzero(regions_df["profile_direction"] == 1)}")
# utils.check_profiles(x)

# regions_df
# regions_df_orig
# 
# 
# prof_summ_df_orig = utils.check_profiles(x_orig)
# prof_summ_df = utils.check_profiles(x)

# between_df_orig = prof_summ_df_orig[prof_summ_df_orig["profile_index"] % 1 == 0.5]
# between_df = prof_summ_df[prof_summ_df["profile_index"] % 1 == 0.5]

# # print((between_df_orig.end_time - between_df_orig.start_time).describe())
# # print((between_df.end_time - between_df.start_time).describe())

# print(abs(between_df_orig.end_depth - between_df_orig.start_depth).describe())
# print(abs(between_df.end_depth - between_df.start_depth).describe())

# prof_summ_df_orig

## Explore SOCIB profiles

In [ ]:
z = xr.load_dataset("/home/sam_woodman_noaa_gov/depfrbyrd_amlr03_sgg3_L1_2023-11-27_data_rt.nc")
z

In [ ]:
# pgutils.get_profiles_new(x, filt_time=20)
p1, p2, p_opt = prof.findProfiles(
        z.time.values,
        z.depth.values,
        stall=20,
        # shake=200, 
        # interrupt = 600,
        # inversion = 10
    )

# orig = ["profile_index_orig", "profile_direction_orig"]
# x = x_orig.rename_vars({"profile_index": orig[0], "profile_direction": orig[1]})
z["profile_index_new"] = ('time', p1, {})
z["profile_direction_new"] = ('time', p2, {})
# x = utils.data_var_reorder(x, (vars_keep + orig))
z

In [ ]:
import matplotlib.pyplot as plt
depth = np.array([4, 4, 3, 2, 3, 4, 4, 5, 6, 6, 6, 5, 4, 4, 5, 3, 2, 3, 1, 1, 0, 4, 4])
x = np.arange(0, len(depth))

profile_index, profile_direction, prof_opt = prof.findProfiles(x, depth)
# %    figure
# %    subplot(3, 1, 1, 'XGrid','on','YGrid','on', 'NextPlot', 'add')
# %    stairs(profile_direction, '-g')
# %    subplot(3, 1, 2, 'XGrid','on','YGrid','on', 'NextPlot', 'add')
# %    plot(depth, '-db')
# %    subplot(3, 1, 3, 'XGrid','on','YGrid','on', 'NextPlot', 'add')
# %    stairs(profile_index, '-r')
# %    [profile_index, profile_direction] = findProfiles(depth, 'stall', 1.5)
# %    stairs(profile_index, '-c')
# %    [profile_index, profile_direction] = ...
# %       findProfiles(depth, 'stall', 1.5, 'inversion', 1.5, 'interrupt', inf)
# %    stairs(profile_index, '-m')

# Plotting
fig, axs = plt.subplots(3, 1, figsize=(10, 8), sharex=True)
axs[0].grid(True)
axs[0].stairs(profile_direction, color='g')
axs[0].set_title('Profile Direction')

axs[1].grid(True)
axs[1].plot(depth, '-db')
axs[1].set_title('Depth')
axs[1].invert_yaxis()

axs[2].grid(True)
axs[2].stairs(profile_index, color='r')
axs[2].set_title('Profile Index')

# Second call with stall parameter
profile_index, profile_direction, _ = prof.findProfiles(x, depth, stall=1.5)
axs[2].stairs(profile_index, color='c', label='stall=1.5')

# Third call with more parameters
profile_index, profile_direction, _ = prof.findProfiles(
    x, depth, stall=1.5, inversion=1.5, interrupt=np.inf)
axs[2].stairs(profile_index, color='m', label='stall=1.5, inversion=1.5, interrupt=inf')

axs[2].legend()
plt.tight_layout()
plt.show()