In [1]:
import os
import numpy as np
# import pandas as pd
import xarray as xr
from pathlib import Path

from esdglider import gcp, paths, slocum, utils

deployment_name = "amlr08-20220513"
mode = "delayed"

### Consistent variables
# Define directories
home = Path.home()
mnt_path = home / "gcs-mnt"
cac_path = home / "standard-glider-files" / "Cache"
config_path = home / "glider-lab" / "deployment-configs"

# Bucket names and paths
data_in_bucket_name = "swfscesd-glider-deployments-data-in"
data_out_bucket_name = "swfscesd-glider-deployments-data-out"

data_in_path = mnt_path / data_in_bucket_name
data_out_path = mnt_path / data_out_bucket_name

glider_paths = paths.get_path_glider(
    deployment_name = deployment_name, 
    mode = mode, 
    config_path = config_path, 
    data_in_path = data_in_path, 
    data_out_path = data_out_path, 
    cac_path = cac_path, 
)

### Mount the relevant bucket(s)
gcp.gcs_mount_bucket(data_out_bucket_name, data_out_path, ro=True)

The mountpoint is not empty, will NOT try to unmount

0

In [2]:
ds_raw = xr.load_dataset(glider_paths["tsrawpath"])
df_raw = ds_raw.to_pandas()
display(ds_raw)

<xarray.Dataset> Size: 105MB
Dimensions:                   (time: 298301)
Coordinates:
  * time                      (time) datetime64[ns] 2MB 2022-05-13T18:57:00.1...
Data variables: (12/38)
    latitude                  (time) float64 2MB nan nan nan nan ... nan nan nan
    longitude                 (time) float64 2MB nan nan nan nan ... nan nan nan
    depth_measured            (time) float64 2MB nan nan nan nan ... nan nan nan
    depth_ctd                 (time) float64 2MB nan nan nan nan ... nan nan nan
    profile_index             (time) float64 2MB 0.5 0.5 0.5 ... 102.5 102.5
    profile_direction         (time) float64 2MB nan nan nan nan ... nan nan nan
    ...                        ...
    commanded_oil_volume      (time) float64 2MB 420.0 nan nan ... nan nan nan
    target_depth              (time) float64 2MB nan nan nan nan ... nan nan nan
    waypoint_latitude         (time) float64 2MB nan nan nan nan ... nan nan nan
    waypoint_longitude        (time) float64 2MB nan nan nan nan ... nan nan nan
    distance_over_ground      (time) float64 2MB nan nan nan nan ... nan nan nan
    source_filename           (time) <U12 14MB '01080000.dbd' ... '01090059.ebd'
Attributes: (12/61)
    Conventions:               CF-1.8
    Metadata_Conventions:      Unidata Dataset Discovery v1.0, COARDS, CF-1.8
    acknowledgment:            This work was supported by funding from NOAA.
    cdm_data_type:             Trajectory
    comment:
    contributor_name:          Christian Reiss, George Watters, Jennifer Wals...
    ...                        ...
    summary:                   This was a test deployment by the NOAA SWFSC E...
    time_coverage_end:         2022-05-16T18:29:30.653000192
    time_coverage_start:       2022-05-13T18:57:00.111000064
    title:                     amlr08-20220513T1857
    transmission_system:       IRIDIUM
    wmo_id:

In [3]:
ds_eng = xr.load_dataset(glider_paths["tsengpath"])
df_eng = ds_eng.to_pandas()
display(ds_eng)

ds_sci = xr.load_dataset(glider_paths["tsscipath"])
df_sci = ds_sci.to_pandas()
display(ds_sci)

<xarray.Dataset> Size: 9MB
Dimensions:               (time: 59822)
Coordinates:
  * time                  (time) datetime64[ns] 479kB 2022-05-13T18:57:09.388...
Data variables: (12/18)
    latitude              (time) float64 479kB 33.17 33.17 33.17 ... 33.17 33.17
    longitude             (time) float64 479kB -117.4 -117.4 ... -117.5 -117.5
    depth                 (time) float64 479kB 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0
    profile_index         (time) float64 479kB 0.5 0.5 0.5 ... 102.5 102.5 102.5
    heading               (time) float64 479kB 4.637 4.637 4.638 ... nan nan nan
    pitch                 (time) float64 479kB -0.1764 -0.193 -0.212 ... nan nan
    ...                    ...
    leak_detect           (time) float64 479kB 2.483 2.482 2.482 ... 2.481 2.481
    leak_detect_forward   (time) float64 479kB 2.476 2.476 2.475 ... 2.473 2.473
    leak_detect_science   (time) float64 479kB 2.478 2.477 2.477 ... 2.475 2.475
    vacuum                (time) float64 479kB 8.34 8.22 8.081 ... 8.53 8.56
    distance_over_ground  (time) float64 479kB 0.0 0.002219 ... 98.91 98.91
    profile_direction     (time) float64 479kB 0.0 0.0 0.0 0.0 ... 0.0 0.0 nan
Attributes: (12/61)
    Conventions:               CF-1.8
    Metadata_Conventions:      Unidata Dataset Discovery v1.0, COARDS, CF-1.8
    acknowledgment:            This work was supported by funding from NOAA.
    cdm_data_type:             Trajectory
    comment:                   Engineering-only timeseries.
    contributor_name:          Christian Reiss, George Watters, Jennifer Wals...
    ...                        ...
    summary:                   This was a test deployment by the NOAA SWFSC E...
    time_coverage_end:         2022-05-16T18:27:26.524000000
    time_coverage_start:       2022-05-13T18:57:09.388999936
    title:                     amlr08-20220513T1857
    transmission_system:       IRIDIUM
    wmo_id:

<xarray.Dataset> Size: 22MB
Dimensions:                   (time: 113066)
Coordinates:
  * time                      (time) datetime64[ns] 905kB 2022-05-13T18:57:22...
Data variables: (12/23)
    latitude                  (time) float64 905kB 33.17 33.17 ... 33.17 33.17
    longitude                 (time) float64 905kB -117.4 -117.4 ... -117.5
    depth                     (time) float64 905kB 0.009929 -0.02979 ... 2.582
    profile_index             (time) float64 905kB 0.5 0.5 0.5 ... 102.0 102.0
    conductivity              (time) float64 905kB 4.289 4.293 ... 4.343 4.348
    temperature               (time) float64 905kB 16.65 16.65 ... 17.11 17.2
    ...                        ...
    pitch                     (time) float64 905kB -0.2286 -0.2451 ... nan nan
    roll                      (time) float64 905kB -0.0175 -0.01644 ... nan nan
    water_velocity_eastward   (time) float64 905kB 0.01107 0.01203 ... nan nan
    water_velocity_northward  (time) float64 905kB -0.01072 -0.01165 ... nan nan
    distance_over_ground      (time) float64 905kB 0.0 0.001398 ... 95.85 95.85
    profile_direction         (time) float64 905kB -1.0 -1.0 1.0 ... -1.0 nan
Attributes: (12/61)
    Conventions:               CF-1.8
    Metadata_Conventions:      Unidata Dataset Discovery v1.0, COARDS, CF-1.8
    acknowledgment:            This work was supported by funding from NOAA.
    cdm_data_type:             Trajectory
    comment:
    contributor_name:          Christian Reiss, George Watters, Jennifer Wals...
    ...                        ...
    summary:                   This was a test deployment by the NOAA SWFSC E...
    time_coverage_end:         2022-05-16T18:26:17.496000000
    time_coverage_start:       2022-05-13T18:57:22.000000000
    title:                     amlr08-20220513T1857
    transmission_system:       IRIDIUM
    wmo_id:

## Profile checks

In [4]:
print("-------ENG")
display(utils.check_profiles(utils.calc_profile_summary(ds_eng, "depth")))
print("-------SCI")
display(utils.check_profiles(utils.calc_profile_summary(ds_sci, "depth")))

print("-------RAW")
prof_summ_raw = utils.calc_profile_summary(ds_raw, "depth_measured")
utils.check_profiles(prof_summ_raw)
print(f"Dives: {np.count_nonzero(prof_summ_raw.profile_direction.values == 1)}")
print(f"Climbs: {np.count_nonzero(prof_summ_raw.profile_direction.values == -1)}")
display(prof_summ_raw)

-------ENG

,profile_index,profile_direction,profile_phase,start_time,end_time,start_depth,end_depth,min_depth,max_depth,depth_range,min_lon,max_lon,min_lat,max_lat,distance_traveled,num_points,time_at_surface_s,profile_duration_s
0,0.5,0.0,surfacing,2022-05-13 18:57:09.388999936,2022-05-13 18:58:38.155000064,0.000000,0.000000,0.000000,0.000000,0.000000,-117.440915,-117.440417,33.167378,33.167505,0.049148,23,88,88.766
1,1.0,1.0,descent,2022-05-13 18:58:42.157999872,2022-05-13 19:02:02.507000064,0.432177,28.678598,0.432177,28.678598,28.246422,-117.440623,-117.440295,33.167284,33.167456,0.049188,51,28,200.349
2,1.5,0.0,inflection,2022-05-13 19:02:06.508999936,2022-05-13 19:02:06.508999936,28.722088,28.722088,28.722088,28.722088,0.000000,-117.440625,-117.440625,33.167283,33.167283,0.000000,1,0,0.000
3,2.0,-1.0,ascent,2022-05-13 19:02:10.563000064,2022-05-13 19:05:58.887000064,28.700344,0.149495,0.149495,28.700344,28.550849,-117.440839,-117.440390,33.166404,33.167280,0.115514,58,28,228.324
4,2.5,0.0,surfacing,2022-05-13 19:06:02.888999936,2022-05-13 19:18:32.158999808,0.000000,0.000000,0.000000,1.410690,1.410690,-117.440315,-117.435067,33.164405,33.166313,0.548333,81,749,749.270
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,100.5,0.0,surfacing,2022-05-16 18:04:17.645999872,2022-05-16 18:11:29.117000192,0.000000,0.000000,0.000000,1.041111,1.041111,-117.452924,-117.452062,33.167860,33.168448,0.129996,83,431,431.471
201,101.0,1.0,descent,2022-05-16 18:11:33.124999936,2022-05-16 18:18:21.752000000,0.214746,56.364037,0.214746,56.364037,56.149291,-117.452435,-117.451973,33.167900,33.168397,0.099573,103,28,408.627
202,101.5,0.0,inflection,2022-05-16 18:18:25.753999872,2022-05-16 18:18:33.765000192,56.385780,56.364037,56.364037,56.385780,0.021744,-117.452443,-117.452435,33.168398,33.168409,0.001490,3,0,8.011
203,102.0,-1.0,ascent,2022-05-16 18:18:37.768000000,2022-05-16 18:26:30.457999872,56.342289,0.345225,0.345225,56.342289,55.997064,-117.452995,-117.452443,33.168409,33.169398,0.187080,117,40,472.690
204,102.5,0.0,surfacing,2022-05-16 18:26:34.466000128,2022-05-16 18:27:26.524000000,0.000000,0.000000,0.000000,0.179346,0.179346,-117.452621,-117.452267,33.168322,33.168831,0.066579,14,52,52.058

-------SCI

 (OPT) The following 23 dives/climbs are not followed by an inflection: 1.0, 10.0, 19.0, 22.0, 25.0, 30.0, 37.0, 38.0, 46.0, 55.0, 61.0, 62.0, 63.0, 66.0, 67.0, 70.0, 77.0, 78.0, 82.0, 86.0, 89.0, 91.0, 95.0
(OPT) The following 18 inflections are not 2-followed by an inflection: 0.5, 9.5, 18.5, 21.5, 24.5, 29.5, 36.5, 45.5, 54.5, 60.5, 65.5, 69.5, 76.5, 81.5, 85.5, 88.5, 90.5, 94.5
(OPT) The following 12 dives are not 2-followed by a climb: 1.0, 19.0, 25.0, 37.0, 55.0, 61.0, 63.0, 67.0, 77.0, 89.0, 91.0, 95.0
(OPT) The following 11 climbs are not 2-followed by a dive: 10.0, 22.0, 30.0, 38.0, 46.0, 62.0, 66.0, 70.0, 78.0, 82.0, 86.0
There are 1 surface profiles that have both a start or end depth >3m, and depth range >3m. Profile indices: 36.5

,profile_index,profile_direction,profile_phase,start_time,end_time,start_depth,end_depth,min_depth,max_depth,depth_range,min_lon,max_lon,min_lat,max_lat,distance_traveled,num_points,time_at_surface_s,profile_duration_s
0,0.5,0.0,surfacing,2022-05-13 18:57:22.000000000,2022-05-13 18:58:38.000000000,0.009929,0.685125,-0.059576,0.685125,0.744702,-117.440840,-117.440417,33.167379,33.167478,0.041459,34,76,76.000
1,1.0,1.0,descent,2022-05-13 18:58:40.000000000,2022-05-13 19:02:06.000000000,0.744701,28.832860,0.744701,28.832860,28.088158,-117.440624,-117.440296,33.167283,33.167456,0.050129,104,30,206.000
2,2.0,-1.0,ascent,2022-05-13 19:02:08.000000000,2022-05-13 19:05:54.186000128,28.803076,1.072369,1.072369,28.803076,27.730706,-117.440838,-117.440478,33.166510,33.167282,0.101511,114,22,226.186
3,2.5,0.0,surfacing,2022-05-13 19:17:28.728000000,2022-05-13 19:18:30.728000000,0.099294,0.456751,0.039717,0.456751,0.417033,-117.435529,-117.435077,33.164409,33.164497,0.045265,32,62,62.000
4,3.0,1.0,descent,2022-05-13 19:18:32.728000000,2022-05-13 19:25:32.729000192,0.417033,56.410921,0.417033,56.430773,56.013739,-117.435662,-117.434835,33.163968,33.164404,0.113206,211,36,420.001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176,100.0,-1.0,ascent,2022-05-16 17:56:09.716000000,2022-05-16 18:03:59.740999936,55.477792,2.869568,2.869568,55.477792,52.608225,-117.453267,-117.452840,33.168096,33.169196,0.179159,235,22,470.025
177,100.5,0.0,surfacing,2022-05-16 18:10:45.713999872,2022-05-16 18:11:27.713999872,0.178729,0.635479,0.129082,0.635479,0.506397,-117.452142,-117.452064,33.168051,33.168063,0.007521,22,42,42.000
178,101.0,1.0,descent,2022-05-16 18:11:29.713999872,2022-05-16 18:18:25.714999808,0.863853,56.768256,0.863853,56.768256,55.904403,-117.452435,-117.451973,33.167901,33.168398,0.100615,209,26,416.001
179,101.5,0.0,inflection,2022-05-16 18:18:27.714999808,2022-05-16 18:18:33.714999808,56.708696,56.678918,56.678918,56.748404,0.069486,-117.452443,-117.452438,33.168401,33.168409,0.000986,4,0,6.000
180,102.0,-1.0,ascent,2022-05-16 18:18:35.714999808,2022-05-16 18:26:17.496000000,56.738478,2.581620,2.581620,56.738478,54.156859,-117.452994,-117.452443,33.168409,33.169395,0.160511,232,21,461.781

-------RAW
Dives: 51
Climbs: 51

,profile_index,profile_direction,profile_phase,start_time,end_time,start_depth,end_depth,min_depth,max_depth,depth_range,min_lon,max_lon,min_lat,max_lat,distance_traveled,num_points,time_at_surface_s,profile_duration_s
0,0.5,0.0,surfacing,2022-05-13 18:57:00.111000064,2022-05-13 18:58:38.155000064,0.000000,0.000000,0.000000,0.000000,0.000000,-117.440915,-117.440417,33.167378,33.167505,NaN,123,88,98.044
1,1.0,1.0,descent,2022-05-13 18:58:39.000000000,2022-05-13 19:02:06.000000000,0.432177,28.678598,0.432177,28.678598,28.246422,-117.440623,-117.440295,33.167284,33.167456,NaN,259,28,207.000
2,1.5,0.0,inflection,2022-05-13 19:02:06.508999936,2022-05-13 19:02:06.508999936,28.722088,28.722088,28.722088,28.722088,0.000000,-117.440625,-117.440625,33.167283,33.167283,0.0,1,0,0.000
3,2.0,-1.0,ascent,2022-05-13 19:02:07.000000000,2022-05-13 19:06:02.186000128,28.700344,0.149495,0.149495,28.700344,28.550849,-117.440839,-117.440633,33.166949,33.167280,NaN,294,28,235.186
4,2.5,0.0,surfacing,2022-05-13 19:06:02.888999936,2022-05-13 19:18:32.158999808,0.000000,0.000000,0.000000,1.410690,1.410690,-117.439865,-117.435067,33.164405,33.165768,NaN,438,749,749.270
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,100.5,0.0,surfacing,2022-05-16 18:04:17.645999872,2022-05-16 18:11:29.117000192,0.000000,0.000000,0.000000,1.041111,1.041111,-117.452657,-117.452062,33.167860,33.168063,NaN,410,431,431.471
201,101.0,1.0,descent,2022-05-16 18:11:29.713999872,2022-05-16 18:18:25.714999808,0.214746,56.364037,0.214746,56.364037,56.149291,-117.452435,-117.451973,33.167900,33.168397,NaN,520,28,416.001
202,101.5,0.0,inflection,2022-05-16 18:18:25.753999872,2022-05-16 18:18:33.765000192,56.385780,56.364037,56.364037,56.385780,0.021744,-117.452443,-117.452435,33.168398,33.168409,NaN,11,0,8.011
203,102.0,-1.0,ascent,2022-05-16 18:18:34.714999808,2022-05-16 18:26:33.496000000,56.342289,0.345225,0.345225,56.342289,55.997064,-117.452995,-117.452443,33.168409,33.169398,NaN,595,40,478.781
204,102.5,0.0,surfacing,2022-05-16 18:26:34.466000128,2022-05-16 18:29:30.653000192,0.000000,0.000000,0.000000,1.853239,1.853239,-117.452288,-117.452267,33.168322,33.168327,NaN,214,172,176.187

In [5]:
d = ds_sci.where(ds_sci.pressure.isnull(), drop = True)
d

<xarray.Dataset> Size: 0B
Dimensions:                   (time: 0)
Coordinates:
  * time                      (time) datetime64[ns] 0B
Data variables: (12/23)
    latitude                  (time) float64 0B
    longitude                 (time) float64 0B
    depth                     (time) float64 0B
    profile_index             (time) float64 0B
    conductivity              (time) float64 0B
    temperature               (time) float64 0B
    ...                        ...
    pitch                     (time) float64 0B
    roll                      (time) float64 0B
    water_velocity_eastward   (time) float64 0B
    water_velocity_northward  (time) float64 0B
    distance_over_ground      (time) float64 0B
    profile_direction         (time) float64 0B
Attributes: (12/61)
    Conventions:               CF-1.8
    Metadata_Conventions:      Unidata Dataset Discovery v1.0, COARDS, CF-1.8
    acknowledgment:            This work was supported by funding from NOAA.
    cdm_data_type:             Trajectory
    comment:
    contributor_name:          Christian Reiss, George Watters, Jennifer Wals...
    ...                        ...
    summary:                   This was a test deployment by the NOAA SWFSC E...
    time_coverage_end:         2022-05-16T18:26:17.496000000
    time_coverage_start:       2022-05-13T18:57:22.000000000
    title:                     amlr08-20220513T1857
    transmission_system:       IRIDIUM
    wmo_id:

In [6]:
# idx_list = 6.5, 8.5, 10.5, 14.5, 18.5, 22.5, 30.5, 34.5, 38.5, 58.5, 74.5, 78.5, 82.5, 86.5, 98.5, 118.5, 122.5, 142.5, 166.5, 174.5, 182.5, 190.5, 194.5, 210.5, 218.5, 222.5, 230.5, 242.5, 250.5, 282.5, 294.5, 306.5, 334.5, 358.5, 370.5, 374.5, 410.5, 424.5, 430.5, 438.5, 442.5, 478.5, 494.5, 498.5, 518.5, 526.5, 530.5, 534.5, 538.5, 550.5, 554.5, 558.5, 566.5, 582.5, 594.5, 602.5, 618.5, 630.5, 646.5, 654.5, 666.5, 670.5, 674.5, 678.5, 690.5, 694.5, 702.5, 706.5, 710.5, 714.5, 722.5, 746.5, 750.5, 754.5, 762.5, 766.5, 770.5
# p1 = utils.check_profiles(ds_sci)
# p1e = p1[np.isin(p1["profile_index"], idx_list)]
# p1e

# ds = ds_raw
# dt = "2023-12-19"
# ds_sub1 = ds.sel(time=slice(f"{dt} 08:00", dt))
# ds_sub1

<!-- ## Testing new profile parameters -->

## Exploring new profile calculations

In [7]:
ds_touse = ds_raw.copy(deep=True)

vars_keep = ["longitude", "latitude", "depth_measured", #"depth_ctd", 
                "profile_index", "profile_direction"]
x_orig = utils.data_var_reorder(ds_touse, vars_keep)
# regions_df_orig = utils.calc_regions(x_orig)
# print(x_orig.profile_index.attrs)

# utils.profileOptionsList #findProf defaults

# pgutils.get_profiles_new(x, filt_time=20)
p1, p2, p_opt = utils.findProfiles(
    x_orig.time.values,
    x_orig.depth_measured.values,
    # stall=5, 
    # shake=19,
    # interrupt=180,
    # inversion=3,
    # length=0,
    # period=0,
)
# # Defaults    
# stall=3, #scalar with the maximum vertical displacement when stalled.
# shake=20, #scalar with the maximum duration of a vertical shake.
# interrupt=180, #scalar with the maximum duration of stalled and/or shake intervals during a cast.
# inversion=3, #scalar with the maximum depth inversion allowed during a cast.
# length=10, #scalar with the minimum depth range a cast must span.
# period=0, #scalar with the minimum duration range a cast must last.

orig = ["profile_index_orig", "profile_direction_orig"]
x = x_orig.rename_vars({"profile_index": orig[0], "profile_direction": orig[1]})
x["profile_index"] = ('time', p1, {})
x["profile_direction"] = ('time', p2, {})
x = utils.data_var_reorder(x, (vars_keep + orig))

# x["dives"] = ('time', gt.utils.calc_dive_number(x.time.values, x.depth.values, dive_depth_threshold=15), {})
# display(x)

ds = x
dt = "2025-04-15"
ds_sub = ds.sel(time=slice(f"{dt} 17:10", dt))
ds_sub

<xarray.Dataset> Size: 0B
Dimensions:                   (time: 0)
Coordinates:
  * time                      (time) datetime64[ns] 0B
Data variables: (12/40)
    longitude                 (time) float64 0B
    latitude                  (time) float64 0B
    depth_measured            (time) float64 0B
    profile_index             (time) float64 0B
    profile_direction         (time) float64 0B
    profile_index_orig        (time) float64 0B
    ...                        ...
    commanded_oil_volume      (time) float64 0B
    target_depth              (time) float64 0B
    waypoint_latitude         (time) float64 0B
    waypoint_longitude        (time) float64 0B
    distance_over_ground      (time) float64 0B
    source_filename           (time) <U12 0B
Attributes: (12/61)
    Conventions:               CF-1.8
    Metadata_Conventions:      Unidata Dataset Discovery v1.0, COARDS, CF-1.8
    acknowledgment:            This work was supported by funding from NOAA.
    cdm_data_type:             Trajectory
    comment:
    contributor_name:          Christian Reiss, George Watters, Jennifer Wals...
    ...                        ...
    summary:                   This was a test deployment by the NOAA SWFSC E...
    time_coverage_end:         2022-05-16T18:29:30.653000192
    time_coverage_start:       2022-05-13T18:57:00.111000064
    title:                     amlr08-20220513T1857
    transmission_system:       IRIDIUM
    wmo_id:

In [8]:
# Check profiles
prof_summ = utils.calc_profile_summary(x, "depth_measured")
utils.check_profiles(prof_summ)
print(f"Dives: {np.count_nonzero(prof_summ.profile_direction.values == 1)}")
print(f"Climbs: {np.count_nonzero(prof_summ.profile_direction.values == -1)}")

# gg = prof_summ[prof_summ.profile_index.isin([6.5, 10.5, 14.5, 18.5, 26.5, 30.5, 50.5, 62.5, 70.5, 78.5, 110.5, 114.5, 158.5, 210.5, 218.5, 222.5, 270.5, 274.5, 346.5, 350.5, 362.5, 430.5, 440.5, 478.5, 482.5, 490.5, 494.5, 510.5, 562.5, 594.5, 602.5, 646.5, 666.5, 702.5, 714.5, 738.5, 764.5, 770.5])]
# display(gg)

prof_summ

Dives: 51
Climbs: 51

,profile_index,profile_direction,profile_phase,start_time,end_time,start_depth,end_depth,min_depth,max_depth,depth_range,min_lon,max_lon,min_lat,max_lat,distance_traveled,num_points,time_at_surface_s,profile_duration_s
0,0.5,0.0,surfacing,2022-05-13 18:57:00.111000064,2022-05-13 18:58:38.155000064,0.000000,0.000000,0.000000,0.000000,0.000000,-117.440915,-117.440417,33.167378,33.167505,NaN,123,88,98.044
1,1.0,1.0,descent,2022-05-13 18:58:39.000000000,2022-05-13 19:02:06.000000000,0.432177,28.678598,0.432177,28.678598,28.246422,-117.440623,-117.440295,33.167284,33.167456,NaN,259,28,207.000
2,1.5,0.0,inflection,2022-05-13 19:02:06.508999936,2022-05-13 19:02:06.508999936,28.722088,28.722088,28.722088,28.722088,0.000000,-117.440625,-117.440625,33.167283,33.167283,0.0,1,0,0.000
3,2.0,-1.0,ascent,2022-05-13 19:02:07.000000000,2022-05-13 19:06:02.186000128,28.700344,0.149495,0.149495,28.700344,28.550849,-117.440839,-117.440633,33.166949,33.167280,NaN,294,28,235.186
4,2.5,0.0,surfacing,2022-05-13 19:06:02.888999936,2022-05-13 19:18:32.158999808,0.000000,0.000000,0.000000,1.410690,1.410690,-117.439865,-117.435067,33.164405,33.165768,NaN,438,749,749.270
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,100.5,0.0,surfacing,2022-05-16 18:04:17.645999872,2022-05-16 18:11:29.117000192,0.000000,0.000000,0.000000,1.041111,1.041111,-117.452657,-117.452062,33.167860,33.168063,NaN,410,431,431.471
201,101.0,1.0,descent,2022-05-16 18:11:29.713999872,2022-05-16 18:18:25.714999808,0.214746,56.364037,0.214746,56.364037,56.149291,-117.452435,-117.451973,33.167900,33.168397,NaN,520,28,416.001
202,101.5,0.0,inflection,2022-05-16 18:18:25.753999872,2022-05-16 18:18:33.765000192,56.385780,56.364037,56.364037,56.385780,0.021744,-117.452443,-117.452435,33.168398,33.168409,NaN,11,0,8.011
203,102.0,-1.0,ascent,2022-05-16 18:18:34.714999808,2022-05-16 18:26:33.496000000,56.342289,0.345225,0.345225,56.342289,55.997064,-117.452995,-117.452443,33.168409,33.169398,NaN,595,40,478.781
204,102.5,0.0,surfacing,2022-05-16 18:26:34.466000128,2022-05-16 18:29:30.653000192,0.000000,0.000000,0.000000,1.853239,1.853239,-117.452288,-117.452267,33.168322,33.168327,NaN,214,172,176.187

In [9]:
# Check profiles on eng and sci datasets
print("ENG------")
x_eng = utils.join_profiles(ds_eng, prof_summ)
prof_summ_eng = utils.calc_profile_summary(x_eng, "depth")
display(utils.check_profiles(prof_summ_eng))

print("SCI------")
x_sci = utils.join_profiles(ds_sci, prof_summ)
prof_summ_sci = utils.calc_profile_summary(x_sci, "depth")
display(utils.check_profiles(prof_summ_sci))

ENG------

,profile_index,profile_direction,profile_phase,start_time,end_time,start_depth,end_depth,min_depth,max_depth,depth_range,min_lon,max_lon,min_lat,max_lat,distance_traveled,num_points,time_at_surface_s,profile_duration_s
0,0.5,0.0,surfacing,2022-05-13 18:57:09.388999936,2022-05-13 18:58:38.155000064,0.000000,0.000000,0.000000,0.000000,0.000000,-117.440915,-117.440417,33.167378,33.167505,0.049148,23,88,88.766
1,1.0,1.0,descent,2022-05-13 18:58:42.157999872,2022-05-13 19:02:02.507000064,0.432177,28.678598,0.432177,28.678598,28.246422,-117.440623,-117.440295,33.167284,33.167456,0.049188,51,28,200.349
2,1.5,0.0,inflection,2022-05-13 19:02:06.508999936,2022-05-13 19:02:06.508999936,28.722088,28.722088,28.722088,28.722088,0.000000,-117.440625,-117.440625,33.167283,33.167283,0.000000,1,0,0.000
3,2.0,-1.0,ascent,2022-05-13 19:02:10.563000064,2022-05-13 19:05:58.887000064,28.700344,0.149495,0.149495,28.700344,28.550849,-117.440839,-117.440390,33.166404,33.167280,0.115514,58,28,228.324
4,2.5,0.0,surfacing,2022-05-13 19:06:02.888999936,2022-05-13 19:18:32.158999808,0.000000,0.000000,0.000000,1.410690,1.410690,-117.440315,-117.435067,33.164405,33.166313,0.548333,81,749,749.270
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,100.5,0.0,surfacing,2022-05-16 18:04:17.645999872,2022-05-16 18:11:29.117000192,0.000000,0.000000,0.000000,1.041111,1.041111,-117.452924,-117.452062,33.167860,33.168448,0.129996,83,431,431.471
201,101.0,1.0,descent,2022-05-16 18:11:33.124999936,2022-05-16 18:18:21.752000000,0.214746,56.364037,0.214746,56.364037,56.149291,-117.452435,-117.451973,33.167900,33.168397,0.099573,103,28,408.627
202,101.5,0.0,inflection,2022-05-16 18:18:25.753999872,2022-05-16 18:18:33.765000192,56.385780,56.364037,56.364037,56.385780,0.021744,-117.452443,-117.452435,33.168398,33.168409,0.001490,3,0,8.011
203,102.0,-1.0,ascent,2022-05-16 18:18:37.768000000,2022-05-16 18:26:30.457999872,56.342289,0.345225,0.345225,56.342289,55.997064,-117.452995,-117.452443,33.168409,33.169398,0.187080,117,40,472.690
204,102.5,0.0,surfacing,2022-05-16 18:26:34.466000128,2022-05-16 18:27:26.524000000,0.000000,0.000000,0.000000,0.179346,0.179346,-117.452621,-117.452267,33.168322,33.168831,0.066579,14,52,52.058

SCI------

 (OPT) The following 23 dives/climbs are not followed by an inflection: 1.0, 10.0, 19.0, 22.0, 25.0, 30.0, 37.0, 38.0, 46.0, 55.0, 61.0, 62.0, 63.0, 66.0, 67.0, 70.0, 77.0, 78.0, 82.0, 86.0, 89.0, 91.0, 95.0
(OPT) The following 18 inflections are not 2-followed by an inflection: 0.5, 9.5, 18.5, 21.5, 24.5, 29.5, 36.5, 45.5, 54.5, 60.5, 65.5, 69.5, 76.5, 81.5, 85.5, 88.5, 90.5, 94.5
(OPT) The following 12 dives are not 2-followed by a climb: 1.0, 19.0, 25.0, 37.0, 55.0, 61.0, 63.0, 67.0, 77.0, 89.0, 91.0, 95.0
(OPT) The following 11 climbs are not 2-followed by a dive: 10.0, 22.0, 30.0, 38.0, 46.0, 62.0, 66.0, 70.0, 78.0, 82.0, 86.0
There are 1 surface profiles that have both a start or end depth >3m, and depth range >3m. Profile indices: 36.5

,profile_index,profile_direction,profile_phase,start_time,end_time,start_depth,end_depth,min_depth,max_depth,depth_range,min_lon,max_lon,min_lat,max_lat,distance_traveled,num_points,time_at_surface_s,profile_duration_s
0,0.5,0.0,surfacing,2022-05-13 18:57:22.000000000,2022-05-13 18:58:38.000000000,0.009929,0.685125,-0.059576,0.685125,0.744702,-117.440840,-117.440417,33.167379,33.167478,0.041459,34,76,76.000
1,1.0,1.0,descent,2022-05-13 18:58:40.000000000,2022-05-13 19:02:06.000000000,0.744701,28.832860,0.744701,28.832860,28.088158,-117.440624,-117.440296,33.167283,33.167456,0.050129,104,30,206.000
2,2.0,-1.0,ascent,2022-05-13 19:02:08.000000000,2022-05-13 19:05:54.186000128,28.803076,1.072369,1.072369,28.803076,27.730706,-117.440838,-117.440478,33.166510,33.167282,0.101511,114,22,226.186
3,2.5,0.0,surfacing,2022-05-13 19:17:28.728000000,2022-05-13 19:18:30.728000000,0.099294,0.456751,0.039717,0.456751,0.417033,-117.435529,-117.435077,33.164409,33.164497,0.045265,32,62,62.000
4,3.0,1.0,descent,2022-05-13 19:18:32.728000000,2022-05-13 19:25:32.729000192,0.417033,56.410921,0.417033,56.430773,56.013739,-117.435662,-117.434835,33.163968,33.164404,0.113206,211,36,420.001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176,100.0,-1.0,ascent,2022-05-16 17:56:09.716000000,2022-05-16 18:03:59.740999936,55.477792,2.869568,2.869568,55.477792,52.608225,-117.453267,-117.452840,33.168096,33.169196,0.179159,235,22,470.025
177,100.5,0.0,surfacing,2022-05-16 18:10:45.713999872,2022-05-16 18:11:27.713999872,0.178729,0.635479,0.129082,0.635479,0.506397,-117.452142,-117.452064,33.168051,33.168063,0.007521,22,42,42.000
178,101.0,1.0,descent,2022-05-16 18:11:29.713999872,2022-05-16 18:18:25.714999808,0.863853,56.768256,0.863853,56.768256,55.904403,-117.452435,-117.451973,33.167901,33.168398,0.100615,209,26,416.001
179,101.5,0.0,inflection,2022-05-16 18:18:27.714999808,2022-05-16 18:18:33.714999808,56.708696,56.678918,56.678918,56.748404,0.069486,-117.452443,-117.452438,33.168401,33.168409,0.000986,4,0,6.000
180,102.0,-1.0,ascent,2022-05-16 18:18:35.714999808,2022-05-16 18:26:17.496000000,56.738478,2.581620,2.581620,56.738478,54.156859,-117.452994,-117.452443,33.168409,33.169395,0.160511,232,21,461.781

In [ ]:
# regions_df_orig = utils.calc_regions(x_orig)
# regions_df = utils.calc_regions(x)
# # display(regions_df)
# # print(np.argwhere(regions_df_orig.profile_description == np.roll(regions_df_orig.profile_description, 1)))

# # print(regions_df["profile_direction"].value_counts())
# print("------------")
# print(f"Climbs orig: {np.count_nonzero(regions_df_orig["profile_direction"] == -1)}")
# print(f"Dives orig: {np.count_nonzero(regions_df_orig["profile_direction"] == 1)}")
# utils.check_profiles(x_orig)

# print("------------")
# print(f"Climbs: {np.count_nonzero(regions_df["profile_direction"] == -1)}")
# print(f"Dives: {np.count_nonzero(regions_df["profile_direction"] == 1)}")
# utils.check_profiles(x)

# regions_df
# regions_df_orig
# 
# 
# prof_summ_df_orig = utils.check_profiles(x_orig)
# prof_summ_df = utils.check_profiles(x)

# between_df_orig = prof_summ_df_orig[prof_summ_df_orig["profile_index"] % 1 == 0.5]
# between_df = prof_summ_df[prof_summ_df["profile_index"] % 1 == 0.5]

# # print((between_df_orig.end_time - between_df_orig.start_time).describe())
# # print((between_df.end_time - between_df.start_time).describe())

# print(abs(between_df_orig.end_depth - between_df_orig.start_depth).describe())
# print(abs(between_df.end_depth - between_df.start_depth).describe())

# prof_summ_df_orig

## Explore SOCIB profiles

In [ ]:
z = xr.load_dataset("/home/sam_woodman_noaa_gov/depfrbyrd_amlr03_sgg3_L1_2023-11-27_data_rt.nc")
z

In [ ]:
# pgutils.get_profiles_new(x, filt_time=20)
p1, p2, p_opt = utils.findProfiles(
        z.time.values,
        z.depth.values,
        stall=20,
        # shake=200, 
        # interrupt = 600,
        # inversion = 10
    )

# orig = ["profile_index_orig", "profile_direction_orig"]
# x = x_orig.rename_vars({"profile_index": orig[0], "profile_direction": orig[1]})
z["profile_index_new"] = ('time', p1, {})
z["profile_direction_new"] = ('time', p2, {})
# x = utils.data_var_reorder(x, (vars_keep + orig))
z

In [ ]:
import matplotlib.pyplot as plt
depth = np.array([4, 4, 3, 2, 3, 4, 4, 5, 6, 6, 6, 5, 4, 4, 5, 3, 2, 3, 1, 1, 0, 4, 4])
x = np.arange(0, len(depth))

profile_index, profile_direction, prof_opt = utils.findProfiles(x, depth)
# %    figure
# %    subplot(3, 1, 1, 'XGrid','on','YGrid','on', 'NextPlot', 'add')
# %    stairs(profile_direction, '-g')
# %    subplot(3, 1, 2, 'XGrid','on','YGrid','on', 'NextPlot', 'add')
# %    plot(depth, '-db')
# %    subplot(3, 1, 3, 'XGrid','on','YGrid','on', 'NextPlot', 'add')
# %    stairs(profile_index, '-r')
# %    [profile_index, profile_direction] = findProfiles(depth, 'stall', 1.5)
# %    stairs(profile_index, '-c')
# %    [profile_index, profile_direction] = ...
# %       findProfiles(depth, 'stall', 1.5, 'inversion', 1.5, 'interrupt', inf)
# %    stairs(profile_index, '-m')

# Plotting
fig, axs = plt.subplots(3, 1, figsize=(10, 8), sharex=True)
axs[0].grid(True)
axs[0].stairs(profile_direction, color='g')
axs[0].set_title('Profile Direction')

axs[1].grid(True)
axs[1].plot(depth, '-db')
axs[1].set_title('Depth')
axs[1].invert_yaxis()

axs[2].grid(True)
axs[2].stairs(profile_index, color='r')
axs[2].set_title('Profile Index')

# Second call with stall parameter
profile_index, profile_direction = utils.findProfiles(x, depth, stall=1.5)
axs[2].stairs(profile_index, color='c', label='stall=1.5')

# Third call with more parameters
profile_index, profile_direction = utils.findProfiles(
    x, depth, stall=1.5, inversion=1.5, interrupt=np.inf)
axs[2].stairs(profile_index, color='m', label='stall=1.5, inversion=1.5, interrupt=inf')

axs[2].legend()
plt.tight_layout()
plt.show()