In [ ]:
import os
import numpy as np
# import pandas as pd
import xarray as xr
from pathlib import Path

from esdglider import gcp, paths, slocum, utils

deployment_name = "amlr08-20220513"
mode = "delayed"

### Consistent variables
# Define directories
home = Path.home()
mnt_path = home / "gcs-mnt"
cac_path = home / "standard-glider-files" / "Cache"
config_path = home / "glider-lab" / "deployment-configs"

# Bucket names and paths
data_in_bucket_name = "swfscesd-glider-deployments-data-in"
data_out_bucket_name = "swfscesd-glider-deployments-data-out"

data_in_path = mnt_path / data_in_bucket_name
data_out_path = mnt_path / data_out_bucket_name

glider_paths = paths.get_path_glider(
    deployment_name = deployment_name, 
    mode = mode, 
    config_path = config_path, 
    data_in_path = data_in_path, 
    data_out_path = data_out_path, 
    cac_path = cac_path, 
)

### Mount the relevant bucket(s)
gcp.gcs_mount_bucket(data_out_bucket_name, data_out_path, ro=True)

The mountpoint is not empty, will NOT try to unmount

0

## Raw dataset

In [4]:
ds_raw = xr.load_dataset(glider_paths["tsrawpath"])
df_raw = ds_raw.to_pandas()
ds_raw

<xarray.Dataset> Size: 105MB
Dimensions:                   (time: 298301)
Coordinates:
  * time                      (time) datetime64[ns] 2MB 2022-05-13T18:57:00.1...
Data variables: (12/38)
    latitude                  (time) float64 2MB nan nan nan nan ... nan nan nan
    longitude                 (time) float64 2MB nan nan nan nan ... nan nan nan
    depth_measured            (time) float64 2MB nan nan nan nan ... nan nan nan
    depth_ctd                 (time) float64 2MB nan nan nan nan ... nan nan nan
    profile_index             (time) float64 2MB 0.5 0.5 0.5 ... 102.5 102.5
    profile_direction         (time) float64 2MB nan nan nan nan ... nan nan nan
    ...                        ...
    commanded_oil_volume      (time) float64 2MB 420.0 nan nan ... nan nan nan
    target_depth              (time) float64 2MB nan nan nan nan ... nan nan nan
    waypoint_latitude         (time) float64 2MB nan nan nan nan ... nan nan nan
    waypoint_longitude        (time) float64 2MB nan nan nan nan ... nan nan nan
    distance_over_ground      (time) float64 2MB nan nan nan nan ... nan nan nan
    source_filename           (time) <U12 14MB '01080000.dbd' ... '01090059.ebd'
Attributes: (12/61)
    Conventions:               CF-1.8
    Metadata_Conventions:      Unidata Dataset Discovery v1.0, COARDS, CF-1.8
    acknowledgment:            This work was supported by funding from NOAA.
    cdm_data_type:             Trajectory
    comment:
    contributor_name:          Christian Reiss, George Watters, Jennifer Wals...
    ...                        ...
    summary:                   This was a test deployment by the NOAA SWFSC E...
    time_coverage_end:         2022-05-16T18:29:30.653000192
    time_coverage_start:       2022-05-13T18:57:00.111000064
    title:                     amlr08-20220513T1857
    transmission_system:       IRIDIUM
    wmo_id:

In [5]:
ds_depth = utils.check_depth(ds_raw["depth_measured"], ds_raw["depth_ctd"])
display(ds_depth)

df_depth = ds_depth.to_pandas()
df_depth = df_depth.sort_values(by="depth_diff_abs", ascending=False) # type: ignore
df_depth

<xarray.Dataset> Size: 14MB
Dimensions:                (time: 298301)
Coordinates:
  * time                   (time) datetime64[ns] 2MB 2022-05-13T18:57:00.1110...
Data variables:
    depth_measured         (time) float64 2MB nan nan nan nan ... nan nan nan
    depth_ctd              (time) float64 2MB nan nan nan nan ... nan nan nan
    depth_measured_interp  (time) float64 2MB nan nan nan nan ... nan nan nan
    depth_diff             (time) float64 2MB nan nan nan nan ... nan nan nan
    depth_diff_abs         (time) float64 2MB nan nan nan nan ... nan nan nan
Attributes:
    source:               m_depth
    long_name:            glider measured depth
    standard_name:        m_depth
    observation_type:     measured
    units:                m
    comment:
    accuracy:
    precision:
    platform:             platform
    resolution:
    ancillary_variables:

,depth_measured,depth_ctd,depth_measured_interp,depth_diff,depth_diff_abs
time,,,,,
2022-05-16 13:33:40.872999936,NaN,63.369509,61.382675,1.986835,1.986835
2022-05-15 06:31:28.000000000,NaN,404.897981,406.875573,1.977592,1.977592
2022-05-15 07:43:07.216999936,NaN,27.403294,25.431949,1.971344,1.971344
2022-05-15 01:44:57.723000064,NaN,362.400216,364.357869,1.957653,1.957653
2022-05-14 23:21:43.332999936,NaN,380.072344,382.003670,1.931326,1.931326
...,...,...,...,...,...
2022-05-16 18:29:26.811000064,0.0,NaN,0.000000,NaN,NaN
2022-05-16 18:29:27.653000192,NaN,NaN,NaN,NaN,NaN
2022-05-16 18:29:28.653000192,NaN,NaN,NaN,NaN,NaN
2022-05-16 18:29:29.653000192,NaN,NaN,NaN,NaN,NaN
2022-05-16 18:29:30.653000192,NaN,NaN,NaN,NaN,NaN

In [6]:
# # Get only depth difference > d
# d = 12
# df_curr = df_depth[df_depth.depth_diff > d]
# df_curr.sort_values(by="time", ascending=True)

# times_wonky = df_curr.index.values
# print("['" + "',\n '".join(times_wonky.astype(str)) + "']")

# display(ds_raw.profile_index.sel(time=times_wonky))

# df_curr

In [7]:
# Explore specific chunks of dataset
ds = utils.data_var_reorder(ds_raw, ["depth_measured", "depth_ctd"])
dt = "2025-04-28"
ds_sub = ds.sel(time=slice(f"{dt} 05:35", dt))
ds_sub

<xarray.Dataset> Size: 0B
Dimensions:                   (time: 0)
Coordinates:
  * time                      (time) datetime64[ns] 0B
Data variables: (12/38)
    depth_measured            (time) float64 0B
    depth_ctd                 (time) float64 0B
    latitude                  (time) float64 0B
    longitude                 (time) float64 0B
    profile_index             (time) float64 0B
    profile_direction         (time) float64 0B
    ...                        ...
    commanded_oil_volume      (time) float64 0B
    target_depth              (time) float64 0B
    waypoint_latitude         (time) float64 0B
    waypoint_longitude        (time) float64 0B
    distance_over_ground      (time) float64 0B
    source_filename           (time) <U12 0B
Attributes: (12/61)
    Conventions:               CF-1.8
    Metadata_Conventions:      Unidata Dataset Discovery v1.0, COARDS, CF-1.8
    acknowledgment:            This work was supported by funding from NOAA.
    cdm_data_type:             Trajectory
    comment:
    contributor_name:          Christian Reiss, George Watters, Jennifer Wals...
    ...                        ...
    summary:                   This was a test deployment by the NOAA SWFSC E...
    time_coverage_end:         2022-05-16T18:29:30.653000192
    time_coverage_start:       2022-05-13T18:57:00.111000064
    title:                     amlr08-20220513T1857
    transmission_system:       IRIDIUM
    wmo_id:

## Science/engineering

In [8]:
ds_eng = xr.load_dataset(glider_paths["tsengpath"])
df_eng = ds_eng.to_pandas()
display(ds_eng)

ds_sci = xr.load_dataset(glider_paths["tsscipath"])
df_sci = ds_sci.to_pandas()
display(ds_sci)

<xarray.Dataset> Size: 9MB
Dimensions:               (time: 59822)
Coordinates:
  * time                  (time) datetime64[ns] 479kB 2022-05-13T18:57:09.388...
Data variables: (12/18)
    latitude              (time) float64 479kB 33.17 33.17 33.17 ... 33.17 33.17
    longitude             (time) float64 479kB -117.4 -117.4 ... -117.5 -117.5
    depth                 (time) float64 479kB 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0
    profile_index         (time) float64 479kB 0.5 0.5 0.5 ... 102.5 102.5 102.5
    heading               (time) float64 479kB 4.637 4.637 4.638 ... nan nan nan
    pitch                 (time) float64 479kB -0.1764 -0.193 -0.212 ... nan nan
    ...                    ...
    leak_detect           (time) float64 479kB 2.483 2.482 2.482 ... 2.481 2.481
    leak_detect_forward   (time) float64 479kB 2.476 2.476 2.475 ... 2.473 2.473
    leak_detect_science   (time) float64 479kB 2.478 2.477 2.477 ... 2.475 2.475
    vacuum                (time) float64 479kB 8.34 8.22 8.081 ... 8.53 8.56
    distance_over_ground  (time) float64 479kB 0.0 0.002219 ... 98.91 98.91
    profile_direction     (time) float64 479kB 0.0 0.0 0.0 0.0 ... 0.0 0.0 nan
Attributes: (12/61)
    Conventions:               CF-1.8
    Metadata_Conventions:      Unidata Dataset Discovery v1.0, COARDS, CF-1.8
    acknowledgment:            This work was supported by funding from NOAA.
    cdm_data_type:             Trajectory
    comment:                   Engineering-only timeseries.
    contributor_name:          Christian Reiss, George Watters, Jennifer Wals...
    ...                        ...
    summary:                   This was a test deployment by the NOAA SWFSC E...
    time_coverage_end:         2022-05-16T18:27:26.524000000
    time_coverage_start:       2022-05-13T18:57:09.388999936
    title:                     amlr08-20220513T1857
    transmission_system:       IRIDIUM
    wmo_id:

<xarray.Dataset> Size: 22MB
Dimensions:                   (time: 113066)
Coordinates:
  * time                      (time) datetime64[ns] 905kB 2022-05-13T18:57:22...
Data variables: (12/23)
    latitude                  (time) float64 905kB 33.17 33.17 ... 33.17 33.17
    longitude                 (time) float64 905kB -117.4 -117.4 ... -117.5
    depth                     (time) float64 905kB 0.009929 -0.02979 ... 2.582
    profile_index             (time) float64 905kB 0.5 0.5 0.5 ... 102.0 102.0
    conductivity              (time) float64 905kB 4.289 4.293 ... 4.343 4.348
    temperature               (time) float64 905kB 16.65 16.65 ... 17.11 17.2
    ...                        ...
    pitch                     (time) float64 905kB -0.2286 -0.2451 ... nan nan
    roll                      (time) float64 905kB -0.0175 -0.01644 ... nan nan
    water_velocity_eastward   (time) float64 905kB 0.01107 0.01203 ... nan nan
    water_velocity_northward  (time) float64 905kB -0.01072 -0.01165 ... nan nan
    distance_over_ground      (time) float64 905kB 0.0 0.001398 ... 95.85 95.85
    profile_direction         (time) float64 905kB -1.0 -1.0 1.0 ... -1.0 nan
Attributes: (12/61)
    Conventions:               CF-1.8
    Metadata_Conventions:      Unidata Dataset Discovery v1.0, COARDS, CF-1.8
    acknowledgment:            This work was supported by funding from NOAA.
    cdm_data_type:             Trajectory
    comment:
    contributor_name:          Christian Reiss, George Watters, Jennifer Wals...
    ...                        ...
    summary:                   This was a test deployment by the NOAA SWFSC E...
    time_coverage_end:         2022-05-16T18:26:17.496000000
    time_coverage_start:       2022-05-13T18:57:22.000000000
    title:                     amlr08-20220513T1857
    transmission_system:       IRIDIUM
    wmo_id:

Science/engineering datasets have been filtered for bogus values
Interpolate the engineering dataset onto the science timestamps, and do the same depth check

In [9]:
ds_depth2 = utils.check_depth(ds_eng["depth"], ds_sci["depth"])
# display(ds_depth2)

df_depth2 = ds_depth2.to_pandas()
df_depth2 = df_depth2.sort_values(by="depth_diff_abs", ascending=False) # type: ignore
df_depth2

,depth_measured,depth_ctd,depth_measured_interp,depth_diff,depth_diff_abs
time,,,,,
2022-05-16 13:33:40.872999936,NaN,63.369380,61.382675,1.986705,1.986705
2022-05-15 06:31:28.000000000,NaN,404.897080,406.875573,1.978494,1.978494
2022-05-15 07:43:07.216999936,NaN,27.403219,25.431949,1.971270,1.971270
2022-05-15 01:44:57.723000064,NaN,362.400599,364.357869,1.957270,1.957270
2022-05-14 23:21:43.332999936,NaN,380.072767,382.003670,1.930902,1.930902
...,...,...,...,...,...
2022-05-16 18:27:10.506000128,0.0,NaN,NaN,NaN,NaN
2022-05-16 18:27:14.508000000,0.0,NaN,NaN,NaN,NaN
2022-05-16 18:27:18.516999936,0.0,NaN,NaN,NaN,NaN
2022-05-16 18:27:22.520999936,0.0,NaN,NaN,NaN,NaN
2022-05-16 18:27:26.524000000,0.0,NaN,NaN,NaN,NaN

In [10]:
# Get the profile indices of the big depth differences
ds_g = ds_depth2.where(ds_depth2.depth_diff_abs > 13, drop=True)
d = ds_sci.profile_index.where(ds_sci.time == ds_g.time, drop=True).values
print(all((d % 1) == 0.5)) # All diffs are between profiles
print(len(d))
d

True
0

array([], dtype=float64)

## SOCIB

In [11]:
# sl1 = xr.load_dataset("/home/sam_woodman_noaa_gov/depfrbyrd_amlr03_sgg3_L1_2023-11-27_data_rt.nc")
# display(sl1)

In [12]:
# sl1["depth_diff"] = sl1.depth - sl1.depth_ctd
# display(sl1.depth_diff.to_pandas().describe())